env:
  TERM: xterm-256color

window:
  decorations_theme_variant: dark

font:
  normal:
    Default:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  bold_italic:
    family: Fira Code
    style: Bold Italic


  size: 13

colors:
  primary:
    background: '#1d2021'
    foreground: '#ebdbb2'

  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#b16286'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

draw_bold_text_with_bright_colors: true
